language: ruby
sudo: false

branches:
  only: master

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - 2.3.0
  - 2.4.0
  - ruby-head

before_install:
  - eval "$(curl -Ss https://raw.githubusercontent.com/neovim/bot-ci/master/scripts/travis-setup.sh) nightly-x64"

env: REPORT_COVERAGE=1
script: travis_retry bundle exec rake --trace
