language: ruby
cache: bundler
sudo: false
dist: trusty

branches:
  only: master

rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - ruby-head

before_install:
  - gem update --system --conservative || (gem install "rubygems-update:~>2.7" --no-document && update_rubygems)
  - gem install --remote bundler || gem install --remote bundler -v "1.17.3"
  - gem install --user-install executable-hooks
  - bundle --version

jobs:
  include:
    - stage: docs
      name: "Generate Docs"
      rvm: 2.6
      env:
        - secure: "ZVvRmjJoHbKdxMWzAssWXA4HpWalDZmRuOXohdRWkfbobYHg2yXmdvLI9A4lNR3C2ejieSfSbd2Rfdg2Ievf2z/fALhXf1B2kZk0mw9RmwgmIjRmoL0l4AG+HZOMrzidfncuVhiv4EVbzTbkkH+HotPHH/+FnEECRMbFDNasEVA="
      script: BUILD=latest bundle exec rake ci:docs

stages:
  - test
  - name: docs
    if: branch = master

env: PATH="$PATH:$PWD/_bin" NVIM_EXECUTABLE="$PWD/_bin/nvim" NVIM_RUBY_LOG_LEVEL=DEBUG NVIM_RUBY_LOG_FILE=ci.log

script: BUILD=nightly bundle exec rake ci:test
