version: '{build}'

environment:
  matrix:
    - RUBY_VERSION: 24
    - RUBY_VERSION: 23
    - RUBY_VERSION: 22

install:
  - set SSL_CERT_FILE=C:/ruby24-x64/ssl/cert.pem
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;C:\tools\neovim\Neovim\bin;%PATH%
  - bundle install

build: off

branches:
  only:
    - master

test_script:
  - bundle exec rake
